### ISSUE TITLE
django app missing

### ISSUE THREAD

**Issue by oyeb** [arrow-/saber#2]
@SouravJaiswal
Make the app which can invoke the game for the `frontend page`. It must return the replay data _(and logs, if specifically requested)_ back to the `frontend`. Then we'll add
- `user db`, history of subs, leaderboard ranking or things like that...
- file submission, proof-reading and compilation. 

You decide how the logs are sent, `json` is fine.

**Comment by SouravJaiswal** [comment]
Will ask ananth to work on this.

**Comment by oyeb** [comment]
Irrelevent now, @ananth95 debuted [saber_backend](https://github.com/ananth95/saber_backend/) which can be seen in action [here](bob16.pythonanywhere.com/arena/)
